
import Head from 'next/head'
import { Button, Box, Container} from '@material-ui/core';
import AnimeList from './AnimeList';
import Router from 'next/router';
import { makeStyles } from '@material-ui/core/styles';
import Typography from '@material-ui/core/Typography';
import SearchBox from './SearchBox'

const useStyles = makeStyles({
    backBtn: {
      border: 0,
      borderRadius: 3,
      marginRight:20
    },
    container: {
        margin:50,
    }
  });
  

export default function AnimeContainer({props}){
    const classes = useStyles();
    const handleCallback = (value) => {
      if(value) Router.push(`/?page=${props.currentPage}&search=${value}`)
      else if(value === ""){
        Router.push(`/?page=${props.currentPage}`)
      }
    }

  return (
  <Container className={classes.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
      <Typography variant="h1">Anime List</Typography>
      <SearchBox parentCallback = {handleCallback} />

        <AnimeList props={props}/>
        <Box display="flex"  mt={3} >
            <Button className={classes.backBtn} disabled={props.currentPage <= 1 || !props.hasNextPage}  onClick={() => Router.push(`/?page=${props.currentPage - 1}`)} variant="contained" >Back</Button>
            <Button onClick={() => Router.push(`/?page=${props.currentPage + 1}`)} variant="contained" color="primary">Next</Button>
        </Box> 
      </main>

      <footer>
      </footer>
    </Container>
  )

}